# Generated by Django 3.1.2 on 2020-11-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Другое', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Имя', max_length=30)),
                ('last_name', models.CharField(default='Фамилия', max_length=30)),
                ('phone', models.CharField(default='0', max_length=20)),
                ('adress', models.CharField(default='Адрес', max_length=100)),
                ('firm_type', models.CharField(choices=[('F', 'Физическое лицо'), ('U', 'Юридическое лицо')], default='', max_length=1)),
                ('photo', models.ImageField(default='', upload_to='people_photos/')),
                ('rating', models.IntegerField(default='5')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='item_image/')),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField(default='Описание товара')),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_shop.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
