# Generated by Django 3.1.2 on 2020-11-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprofile',
            name='label',
            field=models.CharField(default='Название товара', max_length=100),
        ),
    ]
