# Generated by Django 3.1.2 on 2020-11-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_shop', '0002_itemprofile_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Заголовок', max_length=100)),
                ('prev', models.CharField(default='Краткое описание', max_length=500)),
                ('description', models.TextField(default='Новость целиком')),
                ('image', models.ImageField(default='', upload_to='item_news/')),
                ('date', models.DateField()),
            ],
        ),
    ]
