# Generated by Django 3.1.2 on 2020-11-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_shop', '0004_auto_20201106_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnews',
            name='image',
            field=models.ImageField(default='', upload_to='media/item_news/'),
        ),
    ]
