# Generated by Django 3.1.2 on 2020-11-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_shop', '0008_auto_20201106_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='user_icon.png', upload_to='people_photos/'),
        ),
    ]
