# Generated by Django 3.1.2 on 2020-11-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_shop', '0009_auto_20201112_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprofile',
            name='label',
            field=models.CharField(default='Название товара', max_length=100, unique=True),
        ),
    ]
