# Generated by Django 3.1.2 on 2020-12-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_shop', '0010_auto_20201129_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprofile',
            name='description',
            field=models.CharField(default='Описание товара', max_length=20000),
        ),
    ]
