# Generated by Django 3.1.2 on 2020-12-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_shop', '0011_auto_20201211_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprofile',
            name='description',
            field=models.TextField(default='Описание товара'),
        ),
    ]
